export const LANGUAGE_KEY = "preferredLanguage";

export const copy = {
  bn: {
    lang: "বাংলা",
    switchLabel: "ভাষা",
    nav: {
      features: "ফিচার",
      pricing: "প্যাকেজ",
      support: "সাপোর্ট",
      login: "লগইন",
      signup: "সাইন আপ",
      myScore: "আমার স্কোর",
    },
    badge: "হোস্টেল মেস ম্যানেজমেন্ট",
    heroTitle: "মাসিক মেস খরচ হিসাব এখন সহজ এবং স্মার্ট",
    heroDesc:
      "মিল ট্র্যাকিং, বাজার খরচ, ব্যালেন্স এবং রিপোর্ট - সবকিছু এক জায়গায়। মেস ইমেইল বা মোবাইল নম্বর দিয়ে দ্রুত খুঁজে নিন।",
    searchTitle: "আপনার মেস খুঁজুন",
    searchPlaceholder: "ইমেইল, মোবাইল নম্বর বা মেসের নাম লিখুন",
    searchHint: "ইমেইল, মোবাইল নম্বর বা মেসের নাম দিয়ে খুঁজুন (উদাহরণ: hello@mess.com, 01XXXXXXXXX, Ba Mess)",
    searchButton: "সার্চ করুন",
    searchByLabel: "যে তথ্য দিয়ে খুঁজবেন",
    searchByEmail: "ইমেইল",
    searchByPhone: "মোবাইল",
    searchByMessName: "মেস নাম",
    searchLoading: "খোঁজা হচ্ছে...",
    searchRequired: "সার্চ করার জন্য ইমেইল, মোবাইল নম্বর বা মেসের নাম লিখুন।",
    searchFailed: "মেস খোঁজা যায়নি",
    searchNoResults: "কোনো মেস পাওয়া যায়নি। অন্য তথ্য দিয়ে চেষ্টা করুন।",
    searchResultsTitle: "সার্চ ফলাফল",
    searchClose: "বন্ধ করুন",
    searchResultEmail: "ইমেইল",
    searchResultPhone: "মোবাইল",
    requestToAdd: "যোগ করার অনুরোধ",
    enterDashboard: "ড্যাশবোর্ডে প্রবেশ করুন",
    requestDrawerTitle: "যোগদানের অনুরোধ",
    requestDrawerSubTitle: "মেস",
    requestSubmit: "অনুরোধ পাঠান",
    requestSubmitting: "পাঠানো হচ্ছে...",
    requestSuccess: "আপনার অনুরোধ গ্রহণ করা হয়েছে। মেস ম্যানেজার শীঘ্রই যোগাযোগ করবে।",
    requestFailed: "অনুরোধ পাঠানো যায়নি",
    requestInvalidManager: "সঠিক মেস নির্বাচন করা হয়নি",
    requestNoteLabel: "নোট (ঐচ্ছিক)",
    requestNotePlaceholder: "চাইলে একটি ছোট নোট লিখুন",
    accessDrawerTitle: "ড্যাশবোর্ড এক্সেস",
    accessDrawerSubTitle: "মেস",
    accessIdentifierLabel: "ইমেইল অথবা মোবাইল নম্বর",
    accessIdentifierPlaceholder: "ইমেইল অথবা মোবাইল নম্বর লিখুন",
    accessSubmit: "ড্যাশবোর্ডে প্রবেশ করুন",
    accessSubmitting: "যাচাই হচ্ছে...",
    accessRequired: "ইমেইল অথবা মোবাইল নম্বর দিন",
    accessInvalidMess: "সঠিক মেস নির্বাচন করা হয়নি",
    accessNotAccepted: "এই মেসে আপনার অনুরোধ এখনো গৃহীত হয়নি",
    accessFailed: "ড্যাশবোর্ড এক্সেস নেওয়া যায়নি",
    messesTitle: "আমার মেস",
    messesSubtitle: "যেসব মেসে আপনি বর্তমানে সক্রিয় সদস্য, সেগুলো এখানে দেখানো হচ্ছে।",
    messesCheckMyRequest: "আমার রিকোয়েস্ট দেখুন",
    messesLoading: "মেস লোড হচ্ছে...",
    messesEmptyMembership: "আপনি এখনো কোনো মেসের সদস্য নন। সদস্য হতে মেসে রিকোয়েস্ট করুন।",
    messesActiveMemberBadge: "সক্রিয় সদস্য",
    messesJoinedLabel: "যোগদান",
    messesMyRequestTitle: "আমার রিকোয়েস্ট",
    messesMyRequestSubtitle: "আপনার সব যোগদানের রিকোয়েস্টের বর্তমান অবস্থা এখানে দেখুন।",
    messesRequestsLoading: "রিকোয়েস্ট লোড হচ্ছে...",
    messesRequestsEmpty: "কোনো রিকোয়েস্ট পাওয়া যায়নি।",
    messesBack: "ফিরে যান",
    managerPanelLabel: "ম্যানেজার প্যানেল",
    managerNavDashboard: "ড্যাশবোর্ড",
    managerNavProfile: "প্রোফাইল",
    managerNavMembers: "মেম্বারস",
    managerNavMeals: "মিলস",
    managerMembersTitle: "মেম্বারস",
    managerMembersSubtitle: "আপনার মেসের সক্রিয় সব কনজিউমার এখানে দেখুন।",
    managerAddMemberButton: "মেম্বার যোগ করুন",
    managerMembersLoading: "মেম্বার লোড হচ্ছে...",
    managerMembersEmpty: "আপনার মেসে কোনো সক্রিয় মেম্বার পাওয়া যায়নি।",
    managerUnknownConsumer: "অপরিচিত কনজিউমার",
    managerActiveBadge: "সক্রিয়",
    statOne: "সক্রিয় মেস",
    statTwo: "মাসিক ট্রানজেকশন",
    statThree: "অটো রিপোর্ট",
    cards: {
      oneTitle: "বুদ্ধিমান ক্যালকুলেশন",
      oneDesc: "মিল, বাজার ও অতিরিক্ত খরচ স্বয়ংক্রিয়ভাবে ব্যালেন্সে যোগ হয়।",
      twoTitle: "লাইভ আপডেট",
      twoDesc: "Socket সাপোর্টের মাধ্যমে সদস্যরা সাথে সাথে আপডেট দেখতে পাবে।",
      threeTitle: "মোবাইল রেডি",
      threeDesc: "ফোন বা ল্যাপটপ - সব স্ক্রিনে রেসপন্সিভ অভিজ্ঞতা।",
    },
    signupTitle: "নতুন অ্যাকাউন্ট তৈরি করুন",
    signupSubTitle: "৩০ সেকেন্ডে শুরু করুন",
    signupSchemaHint: "মেস ম্যানেজার রেজিস্ট্রেশনের জন্য প্রয়োজনীয় তথ্য দিন",
    signupMessName: "মেসের নাম",
    signupMessNamePlaceholder: "উদাহরণ: Green Leaf Mess",
    signupPhone: "মোবাইল নম্বর",
    signupPhonePlaceholder: "01XXXXXXXXX",
    signupEmail: "ইমেইল",
    signupEmailPlaceholder: "manager@mess.com",
    signupPassword: "পাসওয়ার্ড",
    signupConfirmPassword: "কনফার্ম পাসওয়ার্ড",
    signupLanguage: "ভাষা পছন্দ",
    signupPasswordHint: "কমপক্ষে ৬ অক্ষরের পাসওয়ার্ড দিন",
    passwordMismatch: "পাসওয়ার্ড এবং কনফার্ম পাসওয়ার্ড এক নয়",
    passwordShort: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে",
    phoneLengthError: "মোবাইল নম্বর অবশ্যই ১১ সংখ্যার হতে হবে",
    emailInvalidError: "সঠিক ইমেইল ঠিকানা দিন",
    registrationFailed: "রেজিস্ট্রেশন ব্যর্থ হয়েছে",
    signupSubmitting: "সাইন আপ হচ্ছে...",
    signupSubmitHint: "সাইন আপ করলে আপনার ম্যানেজার অ্যাকাউন্ট তৈরি হবে",
    verifyOtpTitle: "OTP যাচাই করুন",
    verifyOtpSubTitle: "ইমেইলে পাঠানো OTP দিয়ে অ্যাকাউন্ট ভেরিফাই করুন",
    verifyOtpHint: "OTP না পেলে Resend OTP বাটনে ক্লিক করুন",
    verifyOtpLabel: "OTP কোড",
    verifyOtpPlaceholder: "৬ ডিজিট OTP",
    verifyOtpSubmit: "OTP যাচাই করুন",
    verifyOtpSubmitting: "যাচাই হচ্ছে...",
    verifyOtpResend: "আবার OTP পাঠান",
    backToSignup: "সাইন আপে ফিরে যান",
    haveAccount: "আগে থেকেই অ্যাকাউন্ট আছে?",
    goToLogin: "লগইন করুন",
    loginTitle: "আপনার অ্যাকাউন্টে লগইন করুন",
    loginSubTitle: "ফিরে আসায় স্বাগতম",
    formName: "নাম",
    formEmail: "ইমেইল",
    formPhone: "মোবাইল নম্বর",
    formPassword: "পাসওয়ার্ড",
    formSubmit: "অ্যাকাউন্ট খুলুন",
    loginSubmit: "লগইন করুন",
    loginSubmitting: "লগইন হচ্ছে...",
    loginFailed: "লগইন ব্যর্থ হয়েছে",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    forgotTitle: "পাসওয়ার্ড রিসেট করুন",
    forgotSubTitle: "ইমেইলে OTP নিয়ে পাসওয়ার্ড রিসেট করুন",
    forgotDescription:
      "আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেইল দিন, আমরা সেখানে একটি OTP পাঠাবো। OTP যাচাই করে নতুন পাসওয়ার্ড সেট করতে পারবেন।",
    forgotEmailPlaceholder: "আপনার রেজিস্টার করা ইমেইল",
    forgotSubmit: "OTP পাঠান",
    otpHint: "OTP 5 মিনিটের জন্য বৈধ থাকবে",
    backToLogin: "লগইনে ফিরে যান",
    noAccount: "এখনও অ্যাকাউন্ট নেই?",
    goToSignup: "সাইন আপ করুন",
    close: "বন্ধ",
    advantagesBadge: "Melager এর বিশেষ সুবিধা",
    advantagesTitle: "কেন মেস ম্যানেজাররা Melager ব্যবহার করে",
    advantagesDescription:
      "প্রতিদিনের হিসাবকে দ্রুত, নির্ভুল এবং স্বচ্ছ করতে প্রয়োজনীয় সব টুল একটি প্ল্যাটফর্মে।",
    advantagesCards: [
      {
        icon: "activity",
        title: "অটোমেটেড মিল ও খরচ হিসাব",
        description: "দৈনিক মিল ও বাজার এন্ট্রি থেকে মাসিক ব্যালেন্স স্বয়ংক্রিয়ভাবে তৈরি হয়।",
        points: ["ম্যানুয়াল ভুল কমে যায়", "প্রতিটি সদস্যের হিসাব তাৎক্ষণিক আপডেট"],
      },
      {
        icon: "layers",
        title: "এক প্ল্যাটফর্মে সব মডিউল",
        description: "মিল, বাজার, মেম্বার ম্যানেজমেন্ট, রিপোর্ট এবং সেটিংস এক জায়গায়।",
        points: ["আলাদা শিট বা টুলের প্রয়োজন নেই", "নতুন সদস্য অনবোর্ডিং দ্রুত"],
      },
      {
        icon: "users",
        title: "টিম ট্রান্সপারেন্সি",
        description: "সব সদস্য নিজ নিজ ব্যালেন্স এবং আপডেট দেখতে পারে রিয়েলটাইমে।",
        points: ["ভুল বোঝাবুঝি কমে", "দায়িত্ব বণ্টন স্পষ্ট হয়"],
      },
      {
        icon: "chart",
        title: "ডেটা-ড্রিভেন রিপোর্টিং",
        description: "মাসিক সারাংশ, খরচ বিশ্লেষণ এবং দ্রুত সিদ্ধান্তের জন্য ইনসাইট।",
        points: ["খরচ ট্রেন্ড সহজে বোঝা যায়", "পরবর্তী মাসের পরিকল্পনা সহজ হয়"],
      },
      {
        icon: "activity",
        title: "রিয়েলটাইম নোটিফিকেশন",
        description: "মিল এন্ট্রি, খরচ আপডেট বা গুরুত্বপূর্ণ পরিবর্তনের সাথে সাথে নোটিফিকেশন পান।",
        points: ["দ্রুত সিদ্ধান্ত নেয়া যায়", "সব সদস্য আপডেটেড থাকে"],
      },
      {
        icon: "layers",
        title: "সিকিউর ও স্কেলেবল আর্কিটেকচার",
        description: "বৃদ্ধির সাথে তাল মিলিয়ে ডাটা সুরক্ষা ও পারফরম্যান্স বজায় রাখে।",
        points: ["রোল-ভিত্তিক এক্সেস প্রস্তুত", "দীর্ঘমেয়াদে নির্ভরযোগ্য পারফরম্যান্স"],
      },
    ],
    footer: "Melager - আপনার হোস্টেল হিসাবের নির্ভরযোগ্য সঙ্গী",
    footerBrandDescription:
      "মেস ম্যানেজারদের জন্য স্মার্ট প্ল্যাটফর্ম - মিল, বাজার, বকেয়া ও রিপোর্ট একসাথে ম্যানেজ করুন।",
    footerQuickLinksTitle: "দ্রুত লিংক",
    footerContactTitle: "যোগাযোগ",
    footerAddress: "ধানমন্ডি, ঢাকা, বাংলাদেশ",
    footerPhone: "+880 1712 345678",
    footerEmail: "support@melager.com",
    footerNewsletterTitle: "আপডেট পেতে সাবস্ক্রাইব করুন",
    footerNewsletterDesc: "নতুন ফিচার, আপডেট এবং টিপস সবার আগে পেতে ইমেইল দিন।",
    footerNewsletterPlaceholder: "আপনার ইমেইল লিখুন",
    developerTag: "ডেভেলপার টিম",
    developerDrawerTitle: "Melager ডেভেলপার টিম",
    developerDrawerSubTitle: "যারা প্ল্যাটফর্মটি তৈরি ও রক্ষণাবেক্ষণ করছে",
    developerDrawerDescription:
      "প্রোডাক্ট, ব্যাকএন্ড, ফ্রন্টএন্ড ও অপারেশন টিম সমন্বয়ে Melager ধারাবাহিকভাবে আপডেট ও উন্নত করা হচ্ছে।",
    developerFarmName: "NovaNest IT Farm",
    developerFarmTagline: "Product Engineering, Automation, and Scalable Web Systems",
    developerFarmOverview:
      "NovaNest IT Farm হল Melager-এর প্রযুক্তিগত পার্টনার, যারা প্ল্যাটফর্ম ডেভেলপমেন্ট, সিকিউরিটি, এবং পারফরম্যান্স অপ্টিমাইজেশনে কাজ করছে।",
    developerFarmServices: [
      "Full-stack web application development",
      "Cloud deployment and infrastructure management",
      "Realtime architecture and system optimization",
      "Product maintenance and feature delivery",
    ],
    developerFarmWebsiteLabel: "ওয়েবসাইট",
    developerFarmWebsite: "www.novanestit.com",
    developerFarmContactLabel: "ইমেইল",
    developerFarmContact: "contact@novanestit.com",
    developerFooterNote: "টেকনিক্যাল সাপোর্টের জন্য: devsupport@melager.com",
    footerBottom: "© 2026 Melager. সর্বস্বত্ব সংরক্ষিত।",
  },
  en: {
    lang: "English",
    switchLabel: "Language",
    nav: {
      features: "Features",
      pricing: "Pricing",
      support: "Support",
      login: "Login",
      signup: "Sign up",
      myScore: "My Score",
    },
    badge: "Hostel Meal Management",
    heroTitle: "Monthly mess expense management, now simple and smart",
    heroDesc:
      "Track meals, market costs, balances, and reports from one place. Search a mess instantly by email or phone number.",
    searchTitle: "Find your mess",
    searchPlaceholder: "Enter email, phone number, or mess name",
    searchHint: "Search by email, phone number, or mess name (e.g. hello@mess.com, 01XXXXXXXXX, Ba Mess)",
    searchButton: "Search",
    searchByLabel: "Search field",
    searchByEmail: "Email",
    searchByPhone: "Phone",
    searchByMessName: "Mess Name",
    searchLoading: "Searching...",
    searchRequired: "Enter an email, phone number, or mess name to search.",
    searchFailed: "Failed to search managers",
    searchNoResults: "No mess found. Try another email, phone number, or mess name.",
    searchResultsTitle: "Search Results",
    searchClose: "Close results",
    searchResultEmail: "Email",
    searchResultPhone: "Phone",
    requestToAdd: "Request to Add",
    enterDashboard: "Enter to Dashboard",
    requestDrawerTitle: "Request to Join",
    requestDrawerSubTitle: "Mess",
    requestSubmit: "Send Request",
    requestSubmitting: "Sending...",
    requestSuccess: "Your request has been received. The mess manager will contact you soon.",
    requestFailed: "Failed to send request",
    requestInvalidManager: "No valid mess selected",
    requestNoteLabel: "Note (optional)",
    requestNotePlaceholder: "Write a short note if needed",
    accessDrawerTitle: "Dashboard Access",
    accessDrawerSubTitle: "Mess",
    accessIdentifierLabel: "Email or phone number",
    accessIdentifierPlaceholder: "Enter email or phone number",
    accessSubmit: "Enter to Dashboard",
    accessSubmitting: "Verifying...",
    accessRequired: "Provide email or phone number",
    accessInvalidMess: "No valid mess selected",
    accessNotAccepted: "Your request has not been accepted for this mess yet",
    accessFailed: "Unable to access dashboard",
    messesTitle: "My Messes",
    messesSubtitle: "All messes where you are currently an active member.",
    messesCheckMyRequest: "check my request",
    messesLoading: "Loading messes...",
    messesEmptyMembership: "You are not member of any mess. Please request to a mess for membership.",
    messesActiveMemberBadge: "Active Member",
    messesJoinedLabel: "Joined",
    messesMyRequestTitle: "My Request",
    messesMyRequestSubtitle: "All your join requests with live status.",
    messesRequestsLoading: "Loading requests...",
    messesRequestsEmpty: "No requests found.",
    messesBack: "back",
    managerPanelLabel: "Manager Panel",
    managerNavDashboard: "Dashboard",
    managerNavProfile: "Profile",
    managerNavMembers: "Members",
    managerNavMeals: "Meals",
    managerMembersTitle: "Members",
    managerMembersSubtitle: "All active consumers of your mess.",
    managerAddMemberButton: "Add Member",
    managerMembersLoading: "Loading members...",
    managerMembersEmpty: "No active members found for your mess.",
    managerUnknownConsumer: "Unknown Consumer",
    managerActiveBadge: "Active",
    statOne: "Active Messes",
    statTwo: "Monthly Transactions",
    statThree: "Auto Reports",
    cards: {
      oneTitle: "Smart Calculations",
      oneDesc:
        "Meals, market spending, and extra costs are merged automatically into member balances.",
      twoTitle: "Live Updates",
      twoDesc:
        "With socket support, members get instant updates whenever data changes.",
      threeTitle: "Mobile Ready",
      threeDesc: "Built to feel smooth on phones, tablets, and desktop screens.",
    },
    signupTitle: "Create your account",
    signupSubTitle: "Get started in 30 seconds",
    signupSchemaHint: "Provide the required details for manager registration",
    signupMessName: "Mess name",
    signupMessNamePlaceholder: "Example: Green Leaf Mess",
    signupPhone: "Phone number",
    signupPhonePlaceholder: "01XXXXXXXXX",
    signupEmail: "Email",
    signupEmailPlaceholder: "manager@mess.com",
    signupPassword: "Password",
    signupConfirmPassword: "Confirm password",
    signupLanguage: "Language preference",
    signupPasswordHint: "Use at least 6 characters",
    passwordMismatch: "Password and confirm password do not match",
    passwordShort: "Password must be at least 6 characters long",
    phoneLengthError: "Phone number must be exactly 11 digits",
    emailInvalidError: "Please enter a valid email address",
    registrationFailed: "Registration failed",
    signupSubmitting: "Signing up...",
    signupSubmitHint: "Signing up will create your manager account",
    verifyOtpTitle: "Verify OTP",
    verifyOtpSubTitle: "Verify your account using the OTP sent to your email",
    verifyOtpHint: "If you did not receive it, click Resend OTP",
    verifyOtpLabel: "OTP Code",
    verifyOtpPlaceholder: "6 digit OTP",
    verifyOtpSubmit: "Verify OTP",
    verifyOtpSubmitting: "Verifying...",
    verifyOtpResend: "Resend OTP",
    backToSignup: "Back to sign up",
    haveAccount: "Already have an account?",
    goToLogin: "Log in",
    loginTitle: "Log in to your account",
    loginSubTitle: "Welcome back",
    formName: "Full name",
    formEmail: "Email",
    formPhone: "Phone number",
    formPassword: "Password",
    formSubmit: "Create account",
    loginSubmit: "Log in",
    loginSubmitting: "Logging in...",
    loginFailed: "Login failed",
    forgotPassword: "Forgot password?",
    forgotTitle: "Reset your password",
    forgotSubTitle: "Reset password with OTP via email",
    forgotDescription:
      "Enter the email linked to your account and we will send a one-time OTP. Verify it to set a new password.",
    forgotEmailPlaceholder: "Enter your registered email",
    forgotSubmit: "Send OTP",
    otpHint: "OTP will remain valid for 5 minutes",
    backToLogin: "Back to login",
    noAccount: "Don't have an account yet?",
    goToSignup: "Sign up",
    close: "Close",
    advantagesBadge: "Melager Advantages",
    advantagesTitle: "Why Mess Managers Choose Melager",
    advantagesDescription:
      "Everything needed to keep daily operations fast, accurate, and transparent in one streamlined platform.",
    advantagesCards: [
      {
        icon: "activity",
        title: "Automated meal and cost calculations",
        description:
          "Daily meal and market entries automatically generate clean monthly balances.",
        points: [
          "Reduces manual mistakes significantly",
          "Instantly updates member-wise accounting",
        ],
      },
      {
        icon: "layers",
        title: "All modules in one workspace",
        description:
          "Manage meals, markets, members, reports, and settings from a single dashboard.",
        points: [
          "No need for scattered sheets or tools",
          "Faster onboarding for new members",
        ],
      },
      {
        icon: "users",
        title: "Team-wide transparency",
        description:
          "Members can view their balances and updates in real time with clear accountability.",
        points: [
          "Minimizes confusion and disputes",
          "Clarifies responsibility across the mess",
        ],
      },
      {
        icon: "chart",
        title: "Data-driven reporting",
        description:
          "Get monthly summaries and spending insights for smarter, faster decisions.",
        points: [
          "Understand cost trends quickly",
          "Plan the next month with confidence",
        ],
      },
      {
        icon: "activity",
        title: "Real-time notifications",
        description:
          "Get instant notifications for meal entries, expense updates, and important changes.",
        points: [
          "Enables faster decision making",
          "Keeps all members aligned and informed",
        ],
      },
      {
        icon: "layers",
        title: "Secure and scalable architecture",
        description:
          "Maintains data safety and performance as your mess operations continue to grow.",
        points: [
          "Ready for role-based access control",
          "Reliable long-term performance",
        ],
      },
    ],
    footer: "Melager - your trusted hostel accounting partner",
    footerBrandDescription:
      "A smart platform for mess managers to handle meals, markets, balances, and reports from one dashboard.",
    footerQuickLinksTitle: "Quick links",
    footerContactTitle: "Contact",
    footerAddress: "Dhanmondi, Dhaka, Bangladesh",
    footerPhone: "+880 1712 345678",
    footerEmail: "support@melager.com",
    footerNewsletterTitle: "Subscribe for updates",
    footerNewsletterDesc:
      "Get product updates, new feature announcements, and practical tips directly in your inbox.",
    footerNewsletterPlaceholder: "Enter your email",
    developerTag: "Developer Team",
    developerDrawerTitle: "Melager Developer Team",
    developerDrawerSubTitle: "People building and maintaining this platform",
    developerDrawerDescription:
      "Melager is continuously improved by a collaborative product, backend, frontend, and operations team.",
    developerFarmName: "NovaNest IT Farm",
    developerFarmTagline: "Product Engineering, Automation, and Scalable Web Systems",
    developerFarmOverview:
      "NovaNest IT Farm is Melager's technology partner focused on platform development, security, and performance optimization.",
    developerFarmServices: [
      "Full-stack web application development",
      "Cloud deployment and infrastructure management",
      "Realtime architecture and system optimization",
      "Product maintenance and feature delivery",
    ],
    developerFarmWebsiteLabel: "Website",
    developerFarmWebsite: "www.novanestit.com",
    developerFarmContactLabel: "Email",
    developerFarmContact: "contact@novanestit.com",
    developerFooterNote: "For technical support: devsupport@melager.com",
    footerBottom: "© 2026 Melager. All rights reserved.",
  },
};
