export const LANGUAGE_KEY = "preferredLanguage";

export const copy = {
  bn: {
    lang: "বাংলা",
    switchLabel: "ভাষা",
    nav: {
      features: "ফিচার",
      pricing: "প্যাকেজ",
      support: "সাপোর্ট",
      login: "লগইন",
      signup: "সাইন আপ",
    },
    badge: "হোস্টেল মেস ম্যানেজমেন্ট",
    heroTitle: "মাসিক মেস খরচ হিসাব এখন সহজ এবং স্মার্ট",
    heroDesc:
      "মিল ট্র্যাকিং, বাজার খরচ, ব্যালেন্স এবং রিপোর্ট - সবকিছু এক জায়গায়। মেস ইমেইল বা মোবাইল নম্বর দিয়ে দ্রুত খুঁজে নিন।",
    searchTitle: "আপনার মেস খুঁজুন",
    searchPlaceholder: "ইমেইল বা মোবাইল নম্বর লিখুন",
    searchHint: "উদাহরণ: hello@mess.com অথবা 01XXXXXXXXX",
    searchButton: "সার্চ করুন",
    statOne: "সক্রিয় মেস",
    statTwo: "মাসিক ট্রানজেকশন",
    statThree: "অটো রিপোর্ট",
    cards: {
      oneTitle: "বুদ্ধিমান ক্যালকুলেশন",
      oneDesc: "মিল, বাজার ও অতিরিক্ত খরচ স্বয়ংক্রিয়ভাবে ব্যালেন্সে যোগ হয়।",
      twoTitle: "লাইভ আপডেট",
      twoDesc: "Socket সাপোর্টের মাধ্যমে সদস্যরা সাথে সাথে আপডেট দেখতে পাবে।",
      threeTitle: "মোবাইল রেডি",
      threeDesc: "ফোন বা ল্যাপটপ - সব স্ক্রিনে রেসপন্সিভ অভিজ্ঞতা।",
    },
    signupTitle: "নতুন অ্যাকাউন্ট তৈরি করুন",
    signupSubTitle: "৩০ সেকেন্ডে শুরু করুন",
    signupSchemaHint: "মেস ম্যানেজার রেজিস্ট্রেশনের জন্য প্রয়োজনীয় তথ্য দিন",
    signupMessName: "মেসের নাম",
    signupMessNamePlaceholder: "উদাহরণ: Green Leaf Mess",
    signupPhone: "মোবাইল নম্বর",
    signupPhonePlaceholder: "01XXXXXXXXX",
    signupEmail: "ইমেইল",
    signupEmailPlaceholder: "manager@mess.com",
    signupPassword: "পাসওয়ার্ড",
    signupConfirmPassword: "কনফার্ম পাসওয়ার্ড",
    signupLanguage: "ভাষা পছন্দ",
    signupPasswordHint: "কমপক্ষে ৬ অক্ষরের পাসওয়ার্ড দিন",
    passwordMismatch: "পাসওয়ার্ড এবং কনফার্ম পাসওয়ার্ড এক নয়",
    passwordShort: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে",
    signupSubmitHint: "সাইন আপ করলে আপনার ম্যানেজার অ্যাকাউন্ট তৈরি হবে",
    haveAccount: "আগে থেকেই অ্যাকাউন্ট আছে?",
    goToLogin: "লগইন করুন",
    loginTitle: "আপনার অ্যাকাউন্টে লগইন করুন",
    loginSubTitle: "ফিরে আসায় স্বাগতম",
    formName: "নাম",
    formEmail: "ইমেইল",
    formPhone: "মোবাইল নম্বর",
    formPassword: "পাসওয়ার্ড",
    formSubmit: "অ্যাকাউন্ট খুলুন",
    loginSubmit: "লগইন করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    forgotTitle: "পাসওয়ার্ড রিসেট করুন",
    forgotSubTitle: "ইমেইলে OTP নিয়ে পাসওয়ার্ড রিসেট করুন",
    forgotDescription:
      "আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেইল দিন, আমরা সেখানে একটি OTP পাঠাবো। OTP যাচাই করে নতুন পাসওয়ার্ড সেট করতে পারবেন।",
    forgotEmailPlaceholder: "আপনার রেজিস্টার করা ইমেইল",
    forgotSubmit: "OTP পাঠান",
    otpHint: "OTP 5 মিনিটের জন্য বৈধ থাকবে",
    backToLogin: "লগইনে ফিরে যান",
    noAccount: "এখনও অ্যাকাউন্ট নেই?",
    goToSignup: "সাইন আপ করুন",
    close: "বন্ধ",
    footer: "Mess Manager - আপনার হোস্টেল হিসাবের নির্ভরযোগ্য সঙ্গী",
  },
  en: {
    lang: "English",
    switchLabel: "Language",
    nav: {
      features: "Features",
      pricing: "Pricing",
      support: "Support",
      login: "Login",
      signup: "Sign up",
    },
    badge: "Hostel Meal Management",
    heroTitle: "Monthly mess expense management, now simple and smart",
    heroDesc:
      "Track meals, market costs, balances, and reports from one place. Search a mess instantly by email or phone number.",
    searchTitle: "Find your mess",
    searchPlaceholder: "Enter email or phone number",
    searchHint: "Example: hello@mess.com or 01XXXXXXXXX",
    searchButton: "Search",
    statOne: "Active Messes",
    statTwo: "Monthly Transactions",
    statThree: "Auto Reports",
    cards: {
      oneTitle: "Smart Calculations",
      oneDesc:
        "Meals, market spending, and extra costs are merged automatically into member balances.",
      twoTitle: "Live Updates",
      twoDesc:
        "With socket support, members get instant updates whenever data changes.",
      threeTitle: "Mobile Ready",
      threeDesc: "Built to feel smooth on phones, tablets, and desktop screens.",
    },
    signupTitle: "Create your account",
    signupSubTitle: "Get started in 30 seconds",
    signupSchemaHint: "Provide the required details for manager registration",
    signupMessName: "Mess name",
    signupMessNamePlaceholder: "Example: Green Leaf Mess",
    signupPhone: "Phone number",
    signupPhonePlaceholder: "01XXXXXXXXX",
    signupEmail: "Email",
    signupEmailPlaceholder: "manager@mess.com",
    signupPassword: "Password",
    signupConfirmPassword: "Confirm password",
    signupLanguage: "Language preference",
    signupPasswordHint: "Use at least 6 characters",
    passwordMismatch: "Password and confirm password do not match",
    passwordShort: "Password must be at least 6 characters long",
    signupSubmitHint: "Signing up will create your manager account",
    haveAccount: "Already have an account?",
    goToLogin: "Log in",
    loginTitle: "Log in to your account",
    loginSubTitle: "Welcome back",
    formName: "Full name",
    formEmail: "Email",
    formPhone: "Phone number",
    formPassword: "Password",
    formSubmit: "Create account",
    loginSubmit: "Log in",
    forgotPassword: "Forgot password?",
    forgotTitle: "Reset your password",
    forgotSubTitle: "Reset password with OTP via email",
    forgotDescription:
      "Enter the email linked to your account and we will send a one-time OTP. Verify it to set a new password.",
    forgotEmailPlaceholder: "Enter your registered email",
    forgotSubmit: "Send OTP",
    otpHint: "OTP will remain valid for 5 minutes",
    backToLogin: "Back to login",
    noAccount: "Don't have an account yet?",
    goToSignup: "Sign up",
    close: "Close",
    footer: "Mess Manager - your trusted hostel accounting partner",
  },
};
